# Generated by Django 4.2.30 on 2026-08-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('certificado_calibracion', models.FileField(blank=True, null=True, upload_to='certificados_equipos/')),
                ('fecha_calibracion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Equipo de medición',
                'verbose_name_plural': 'Equipos de medición',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NormaAplicable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Norma aplicable',
                'verbose_name_plural': 'Normas aplicables',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
