# Generated by Django 4.2.30 on 2026-08-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChecklistPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ítem de checklist (plantilla)',
                'verbose_name_plural': 'Ítems de checklist (plantilla)',
                'ordering': ['sistema', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='SistemaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('variantes_disponibles', models.JSONField(blank=True, default=list, help_text='Ej. ["Principal", "Auxiliar"] o ["Izquierdo", "Derecho"]. Vacío si no aplica.')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas_checklist', to='equipos.tipoequipo')),
            ],
            options={
                'verbose_name': 'Sistema de checklist',
                'verbose_name_plural': 'Sistemas de checklist',
                'ordering': ['tipo_equipo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variante', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('NA', 'No aplica')], max_length=2, null=True)),
                ('observacion', models.CharField(blank=True, max_length=500)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='checklist.itemchecklistplantilla')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_checklist', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Respuesta de checklist',
                'verbose_name_plural': 'Respuestas de checklist',
                'ordering': ['servicio', 'item'],
                'unique_together': {('servicio', 'item', 'variante')},
            },
        ),
        migrations.AddField(
            model_name='itemchecklistplantilla',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.sistemachecklist'),
        ),
        migrations.CreateModel(
            name='FotoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='checklist_fotos/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='checklist.respuestachecklist')),
            ],
            options={
                'ordering': ['respuesta', 'orden'],
            },
        ),
    ]
