# Generated by Django 4.2.30 on 2026-08-26 22:47

from django.db import migrations

TIPO_EQUIPO_NOMBRE = "Grúa pórtico"

# Códigos repetidos entre sistemas distintos (ej. "1.1" en Polipasto y en Componentes
# eléctricos del polipasto) son intencionales: reflejan que el Excel MNT-F-001 reinicia
# la numeración por sección. No hay conflicto porque el código vive bajo cada
# SistemaChecklist (FK), no es un campo único global.
SISTEMAS = [
    {
        "nombre": "Polipasto",
        "variantes_disponibles": ["Principal", "Auxiliar"],
        "items": [
            ("1.1", "Verificación y apriete de grapas de fijación del cable al tambor de enrollamiento"),
            ("1.2", "Inspección estado del tambor y ranuras, desgaste"),
            ("1.3", "Verificar cuñas de fijación del cable de acero"),
            ("1.4", "Inspección estado del cable de acero (cocadas, hebras cortadas, aplastamiento, distorsión)"),
            ("1.5", "Torsión de cable de acero y medida"),
            ("1.11", "Resorte de amortiguador de la cadena"),
            ("1.12", "Estado de roamiento de los ganchos"),
            ("1.13", "Inspección poleas inferiores y superiores"),
            ("1.14", "Rodamientos de las poleas"),
            ("1.15", "Revisar estado del gancho, desgaste y deformación"),
            ("1.16", "Estado de los seguros de gancho, lengüeta, resorte, pasador"),
            ("1.17", "Caja(s) reductora(s)"),
            ("1.18", "Revisar nivel del aceite y estado"),
        ],
    },
    {
        "nombre": "Componentes eléctricos del polipasto",
        "variantes_disponibles": ["Principal", "Auxiliar"],
        "items": [
            ("1.1", "Estado de gabinete, puertas, chapas, hermetismo tableros, seguros, pintura, etc."),
            ("1.2", "Prensaestopas en general"),
            ("1.3", "Variadores de frecuencia"),
            ("1.4", "Resistencias de frenado"),
            ("1.5", "Contactores de inversor"),
            ("1.6", "Contactor tetra polar"),
            ("1.7", "Contactos auxiliares"),
            ("1.8", "Protecciones (fusibles, termomagnéticos, guardamotor)"),
            ("1.9", "Contactor de freno"),
            ("1.10", "Rectificador"),
            ("1.11", "Sistemas indicador de carga (LIS-AV, LIS-SV, LIS-SE, otros)"),
            ("1.12", "Apriete y conexiones de enchufes"),
            ("1.13", "Estado de canalizaciones, bandejas, prensaestopas, flexibles, otros"),
            ("1.14", "Bobina del freno"),
            ("1.15", "Estado de freno con la medida del momento (izaje)"),
            ("1.16", "Inspeccionar rectificador de freno"),
            ("1.17", "Motores de izaje"),
            ("1.18", "Dispositivo de sobrecarga"),
            ("1.19", "Limit switch subida"),
            ("1.20", "Limit switch bajada"),
            ("1.21", "Limit switch de seguridad"),
        ],
    },
    {
        "nombre": "Trolley Principal",
        "variantes_disponibles": ["Izquierda", "Derecha"],
        "items": [
            ("3.1", "Pernos de sujeción de testeras"),
            ("3.2", "Motores eléctricos"),
            ("3.3", "Reductores"),
            ("3.4", "Inspección y calibración de frenos de los motores"),
            ("3.5", "Inspección de rectificadores de freno"),
            ("3.6", "Estado de Limit Switch"),
            ("3.7", "Barras actuadoras de Limit Switch"),
            ("3.8", "Estado de eje transmisión del carro"),
            ("3.9", "Ruedas"),
            ("3.10", "Topes mecánicos"),
            ("3.11", "Topes de goma"),
            ("3.12", "Barredores de rieles"),
            ("3.13", "Garra descarrilamiento y antisísmico"),
        ],
    },
    {
        "nombre": "Componentes carro y/o trolley",
        "variantes_disponibles": [],
        "items": [
            ("2.1", "Contactores de inversores de giro"),
            ("2.2", "Contactor tetrapolar"),
            ("2.3", "Contactos auxiliares"),
            ("2.4", "Protecciones (fusibles, termomagnético, guardamotor)"),
            ("2.5", "Contactor de freno"),
            ("2.6", "Límites (inductivos, de cruceta, accionamiento por palanca, proximidad)"),
            ("2.7", "Contactores de control"),
            ("2.8", "Variadores de frecuencia"),
            ("2.9", "Resistencias"),
            ("2.10", "Apriete de conexiones y enchufes"),
            ("2.11", "Estado de canalizaciones, bandejas, prensaestopas, flexibles, gabinetes, otros"),
            ("2.12", "Bobina del freno"),
            ("2.13", "Rectificador"),
            ("2.14", "Estado de carros porta cables deslizables, arrastre, fijo alimentación y control"),
            ("2.15", "Estado de brazo de arrastre"),
            ("2.16", "Motores de traslación"),
            ("2.17", "Limit switch izquierda"),
            ("2.18", "Limit switch derecha"),
        ],
    },
    {
        "nombre": "Puente / Pluma",
        "variantes_disponibles": [],
        "items": [
            ("4.1", "Estado de viga cajones"),
            ("4.2", "Estado de los testeros"),
            ("4.3", "Topes mecánicos"),
            ("4.4", "Topes de goma"),
            ("4.5", "Barredores de riel"),
            ("4.6", "Estado de riel de rodadura de puente y/o pluma"),
            ("4.7", "Estado de vía de rodadura"),
            ("4.8", "Estado de los pernos de sujeción de testero y viga tipo cajón"),
            ("4.9", "Motorreductores"),
            ("4.10", "Eje de transmisión de puente"),
            ("4.11", "Inspección y calibración de frenos de los motores"),
            ("4.12", "Inspección de rectificador de freno"),
            ("4.13", "Estado de Limit Switch"),
            ("4.14", "Barras actuadoras de Limit Switch"),
            ("4.15", "Inspección de piñón de transmisión de ruedas"),
            ("4.16", "Estado de la plataforma de servicio y/o mantenimiento"),
            ("4.17", "Estado escalera de acceso"),
        ],
    },
    {
        "nombre": "Componentes eléctricos puente",
        "variantes_disponibles": [],
        "items": [
            ("3.1", "Estado de gabinete, puertas, chapas, hermetismo tableros, seguros, pintura, etc."),
            ("3.2", "Prensaestopas en general"),
            ("3.3", "Variadores de frecuencia"),
            ("3.4", "Resistencias de frenado"),
            ("3.5", "Contactores de inversores de giro"),
            ("3.6", "Contactor tetrapolar"),
            ("3.7", "Contactos auxiliares"),
            ("3.8", "Protecciones (fusibles, termomagnéticos, guardamotor)"),
            ("3.9", "Contactor de freno"),
            ("3.10", "Rectificador de freno"),
            ("3.11", "Transformador de control"),
            ("3.12", "Contactor principal"),
            ("3.13", "Apriete y conexiones de enchufes"),
            ("3.14", "Estado de canalizaciones, bandejas, prensaestopas, flexibles, otros"),
            ("3.15", "Estado de relés de contactos"),
        ],
    },
    {
        "nombre": "Sistemas de alimentación",
        "variantes_disponibles": ["Barras encapsuladas", "Festoon"],
        "items": [
            ("4.1", "Barras encapsuladas, enrollador"),
            ("4.2", "Carro toma corriente colector"),
            ("4.3", "Brazo de arrastre"),
            ("4.4", "Tapa inicial y final de barras"),
            ("4.5", "Empalmes y uniones"),
            ("4.6", "Cables planos alimentación"),
            ("4.7", "Soporte de barra encapsuladas y/o riel C"),
            ("4.8", "Rieles tipo C"),
            ("4.9", "Carros porta cable deslizantes, arrastre y fijo"),
        ],
    },
    {
        "nombre": "Sistemas de mando",
        "variantes_disponibles": ["Botonera", "Radio control"],
        "items": [
            ("5.1", "Estado de mando control"),
            ("5.2", "Estado de los joystick / palancas"),
            ("5.3", "Estado de carcasa"),
            ("5.4", "Estado de los pulsadores de goma"),
            ("5.5", "Parada de emergencia"),
            ("5.6", "Selector de gancho"),
            ("5.7", "Indicador de movimientos"),
            ("5.8", "Estado de cable de control"),
            ("5.9", "Estado de enchufes de la botonera y/o inalámbrico"),
        ],
    },
    {
        "nombre": "Sistema audio visual",
        "variantes_disponibles": [],
        "items": [
            ("6.1", "Estado sirena"),
            ("6.2", "Estado de circulina"),
            ("6.3", "Luminarias"),
            ("6.4", "Display indicador de peso"),
            ("6.5", "Señales de movimiento de operación"),
            ("6.6", "Indicador de capacidad"),
            ("6.7", "Indicador de movimiento"),
        ],
    },
    {
        "nombre": "Otros",
        "variantes_disponibles": [],
        "items": [
            ("5.1", "Limpieza general"),
            ("5.2", "Pintura"),
            ("5.3", "Soldadura"),
        ],
    },
]

NOMBRES_SISTEMAS = [sistema["nombre"] for sistema in SISTEMAS]


def cargar_plantilla(apps, schema_editor):
    TipoEquipo = apps.get_model("equipos", "TipoEquipo")
    SistemaChecklist = apps.get_model("checklist", "SistemaChecklist")
    ItemChecklistPlantilla = apps.get_model("checklist", "ItemChecklistPlantilla")

    tipo_equipo, _ = TipoEquipo.objects.get_or_create(nombre=TIPO_EQUIPO_NOMBRE)

    for orden_sistema, sistema_data in enumerate(SISTEMAS, start=1):
        sistema = SistemaChecklist.objects.create(
            tipo_equipo=tipo_equipo,
            nombre=sistema_data["nombre"],
            orden=orden_sistema,
            variantes_disponibles=sistema_data["variantes_disponibles"],
        )
        items = [
            ItemChecklistPlantilla(
                sistema=sistema,
                codigo=codigo,
                descripcion=descripcion,
                orden=orden_item,
            )
            for orden_item, (codigo, descripcion) in enumerate(sistema_data["items"])
        ]
        ItemChecklistPlantilla.objects.bulk_create(items)


def eliminar_plantilla(apps, schema_editor):
    """Borra los SistemaChecklist (e ItemChecklistPlantilla en cascada) creados por esta
    migración. No borra el TipoEquipo 'Grúa pórtico': puede haber sido creado por esta
    migración o ya existir de antes con Equipos asociados (PROTECT), así que no es seguro
    eliminarlo automáticamente."""
    TipoEquipo = apps.get_model("equipos", "TipoEquipo")
    SistemaChecklist = apps.get_model("checklist", "SistemaChecklist")

    try:
        tipo_equipo = TipoEquipo.objects.get(nombre=TIPO_EQUIPO_NOMBRE)
    except TipoEquipo.DoesNotExist:
        return
    SistemaChecklist.objects.filter(tipo_equipo=tipo_equipo, nombre__in=NOMBRES_SISTEMAS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0001_initial"),
        ("equipos", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(cargar_plantilla, eliminar_plantilla),
    ]
