# Generated by Django 4.2.30 on 2026-08-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_cargar_plantilla_grua_portico'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklistplantilla',
            name='texto_plantilla',
            field=models.TextField(blank=True, help_text='Párrafo narrativo para el cuerpo del informe. Placeholders opcionales resueltos con str.format(): {nombre_item}, {variante}, {resultado_por_estado}.'),
        ),
    ]
