# Generated by Django 4.2.30

from django.db import migrations

# Redacción tomada o adaptada del informe real JP-F-007 (INF-12625-OT-183-2024, en
# referencias/) donde existe correspondencia directa con el ítem; para el resto se redactó
# en el mismo registro técnico (verbo de acción + componente + qué se verifica).
# Clave: (nombre_sistema, codigo) -> texto_plantilla. codigo no es único globalmente, solo
# dentro de su sistema, así que la clave compuesta es necesaria.
TEXTOS = {
    "Polipasto": {
        "1.1": "Se realizó la verificación y el apriete de las grapas de fijación del cable de acero al tambor de enrollamiento. {resultado_por_estado}",
        "1.2": "Se realizó la inspección del tambor de enrollamiento y sus ranuras, verificando desgaste, deformación y acumulación de suciedad; se procedió a engrasar la corona del tambor. {resultado_por_estado}",
        "1.3": "Se verificaron las cuñas de fijación del cable de acero, comprobando su ajuste y capacidad de retención. {resultado_por_estado}",
        "1.4": "Se realizó limpieza e inspección del cable de acero de izaje para comprobar posibles defectos externos, deformaciones, roturas, corrosión, desgaste y lubricación insuficiente. {resultado_por_estado}",
        "1.5": "Se realizó la medición de la torsión del cable de acero de izaje, comparando el valor obtenido en campo contra el especificado por el fabricante. {resultado_por_estado}",
        "1.11": "Se realizó la inspección del resorte amortiguador de la cadena, verificando su elasticidad y ausencia de fisuras o deformación permanente. {resultado_por_estado}",
        "1.12": "Se realizó la inspección del rodamiento de giro del gancho, verificando juego axial, lubricación y libre giro. {resultado_por_estado}",
        "1.13": "Se realizó la inspección de las poleas de compensación inferiores y superiores, así como de los puntos fijos y el guiador de cable. {resultado_por_estado}",
        "1.14": "Se realizó la inspección y lubricación de los rodamientos de las poleas, verificando ausencia de juego excesivo, ruido o sobrecalentamiento. {resultado_por_estado}",
        "1.15": "Se realizó la inspección y toma de medidas de {nombre_item}, verificando que la apertura de su garganta no exceda el 10% ni ¼” según la norma ASME B30.10, así como su giro. {resultado_por_estado}",
        "1.16": "Se realizó la inspección del seguro del gancho (lengüeta, resorte y pasador), verificando su correcto accionamiento y cierre. {resultado_por_estado}",
        "1.17": "Se realizó la inspección de la(s) caja(s) reductora(s) de izaje, verificando fugas, ruido y vibración anormal. {resultado_por_estado}",
        "1.18": "Se realizó la revisión del nivel y estado del aceite de la caja reductora, procediendo con la lubricación correspondiente. {resultado_por_estado}",
    },
    "Componentes eléctricos del polipasto": {
        "1.1": "Se realizó la inspección de los tableros de fuerza y control del polipasto: gabinete, puertas, chapas, hermetismo, seguros y estado de pintura, aplicando limpia contacto y ajustando terminales y bornes. {resultado_por_estado}",
        "1.2": "Se realizó la inspección de los prensaestopas del tablero, verificando su hermeticidad y correcto ajuste. {resultado_por_estado}",
        "1.3": "Se realizó la inspección y limpieza de los variadores de frecuencia, verificando parámetros de configuración y ausencia de fallas registradas. {resultado_por_estado}",
        "1.4": "Se realizó la inspección de las resistencias de frenado, verificando continuidad y estado físico. {resultado_por_estado}",
        "1.5": "Se realizó la inspección y limpieza de los contactores del inversor de giro. {resultado_por_estado}",
        "1.6": "Se realizó la inspección y limpieza del contactor tetrapolar. {resultado_por_estado}",
        "1.7": "Se realizó la inspección de los contactos auxiliares, verificando continuidad y ausencia de picaduras por arco. {resultado_por_estado}",
        "1.8": "Se realizó la inspección de las protecciones eléctricas (fusibles, termomagnéticos y guardamotor), verificando su calibración y estado. {resultado_por_estado}",
        "1.9": "Se realizó la inspección y limpieza del contactor de freno. {resultado_por_estado}",
        "1.10": "Se realizó la inspección del rectificador, verificando su tensión de salida. {resultado_por_estado}",
        "1.11": "Se realizó la inspección del sistema indicador de carga ({nombre_item}), verificando su correcto funcionamiento. {resultado_por_estado}",
        "1.12": "Se realizó el apriete y verificación de las conexiones de los enchufes del tablero. {resultado_por_estado}",
        "1.13": "Se realizó la inspección de las canalizaciones, bandejas, prensaestopas y flexibles eléctricos, verificando su fijación y estado físico. {resultado_por_estado}",
        "1.14": "Se realizó la inspección de la bobina del freno, verificando su resistencia y ausencia de recalentamiento. {resultado_por_estado}",
        "1.15": "Se realizó la inspección y verificación del freno del motor de izaje, midiendo el espesor del disco de freno y ajustando el air gap de acuerdo con lo recomendado por el fabricante. {resultado_por_estado}",
        "1.16": "Se realizó la inspección del rectificador de freno de izaje. {resultado_por_estado}",
        "1.17": "Se realizó la inspección física del motor de izaje, verificando fijación, temperatura, ruido y vibración durante su operación. {resultado_por_estado}",
        "1.18": "Se realizó la inspección, limpieza y mantenimiento del sistema de sobrecarga del equipo. {resultado_por_estado}",
        "1.19": "Se realizó la inspección, limpieza, ajuste de terminales y mantenimiento del limit switch de subida del polipasto. {resultado_por_estado}",
        "1.20": "Se realizó la inspección, limpieza, ajuste de terminales y mantenimiento del limit switch de bajada del polipasto. {resultado_por_estado}",
        "1.21": "Se realizó la inspección, limpieza, ajuste de terminales y mantenimiento del limit switch de seguridad del polipasto. {resultado_por_estado}",
    },
    "Trolley Principal": {
        "3.1": "Se realizó la verificación del apriete de los pernos de sujeción de las testeras del trolley. {resultado_por_estado}",
        "3.2": "Se realizó la inspección física de los motores eléctricos de traslación del trolley, verificando fijación, temperatura y vibración. {resultado_por_estado}",
        "3.3": "Se realizó la inspección de los reductores de traslación del trolley, verificando fugas, ruido y nivel de aceite. {resultado_por_estado}",
        "3.4": "Se realizó la inspección y calibración del freno del motor de traslación del trolley; al ser un motor con freno compacto de corriente continua, se ajustó el entrehierro entre 0.2 y 0.3 mm según lo recomendado por el fabricante. {resultado_por_estado}",
        "3.5": "Se realizó la inspección del rectificador de freno del motor de traslación del trolley. {resultado_por_estado}",
        "3.6": "Se realizó la inspección del limit switch de traslación del trolley, verificando su correcto accionamiento. {resultado_por_estado}",
        "3.7": "Se realizó la inspección de las barras actuadoras del limit switch del trolley, verificando su fijación y alineación. {resultado_por_estado}",
        "3.8": "Se realizó la inspección del eje de transmisión del carro, verificando alineación, acoples y ausencia de juego excesivo. {resultado_por_estado}",
        "3.9": "Se realizó la inspección de las ruedas del trolley, verificando desgaste de banda de rodadura, pestañas y lubricación de sus rodamientos. {resultado_por_estado}",
        "3.10": "Se realizó la inspección de la ubicación y fijación de los topes mecánicos del trolley, verificando que no exista riesgo de choque contra la plataforma de servicio u otros elementos del equipo. {resultado_por_estado}",
        "3.11": "Se realizó la inspección de los topes de goma del trolley, verificando su fijación y estado de desgaste. {resultado_por_estado}",
        "3.12": "Se realizó la inspección de los barredores de riel del trolley, verificando su fijación y contacto con el riel. {resultado_por_estado}",
        "3.13": "Se realizó la inspección de la garra antidescarrilamiento y del dispositivo antisísmico del trolley, verificando su fijación y holgura respecto al riel. {resultado_por_estado}",
    },
    "Componentes carro y/o trolley": {
        "2.1": "Se realizó la inspección y limpieza de los contactores del inversor de giro del carro. {resultado_por_estado}",
        "2.2": "Se realizó la inspección y limpieza del contactor tetrapolar del carro. {resultado_por_estado}",
        "2.3": "Se realizó la inspección de los contactos auxiliares del tablero del carro. {resultado_por_estado}",
        "2.4": "Se realizó la inspección de las protecciones eléctricas del carro (fusibles, termomagnético y guardamotor). {resultado_por_estado}",
        "2.5": "Se realizó la inspección y limpieza del contactor de freno del carro. {resultado_por_estado}",
        "2.6": "Se realizó la inspección, limpieza, ajuste de terminales y mantenimiento del limitador de velocidad tipo cruceta del trolley. {resultado_por_estado}",
        "2.7": "Se realizó la inspección y limpieza de los contactores de control del carro. {resultado_por_estado}",
        "2.8": "Se realizó la inspección de los variadores de frecuencia del carro, verificando parámetros de configuración. {resultado_por_estado}",
        "2.9": "Se realizó la inspección de las resistencias del circuito de control del carro, verificando continuidad. {resultado_por_estado}",
        "2.10": "Se realizó el apriete y verificación de las conexiones y enchufes del tablero del carro. {resultado_por_estado}",
        "2.11": "Se realizó la inspección de las canalizaciones, bandejas, prensaestopas, flexibles y gabinetes eléctricos del carro. {resultado_por_estado}",
        "2.12": "Se realizó la inspección de la bobina del freno del motor de traslación del carro. {resultado_por_estado}",
        "2.13": "Se realizó la inspección del rectificador de freno del carro. {resultado_por_estado}",
        "2.14": "Se realizó la inspección de los carros porta cable deslizables, de arrastre y fijos de alimentación y control del carro. {resultado_por_estado}",
        "2.15": "Se realizó la inspección del brazo de arrastre del carro, verificando su fijación y alineación. {resultado_por_estado}",
        "2.16": "Se realizó la inspección física de los motores de traslación del carro, verificando fijación, temperatura y vibración. {resultado_por_estado}",
        "2.17": "Se realizó la inspección del limit switch de traslación izquierda del carro. {resultado_por_estado}",
        "2.18": "Se realizó la inspección del limit switch de traslación derecha del carro. {resultado_por_estado}",
    },
    "Puente / Pluma": {
        "4.1": "Se realizó la inspección visual de la viga tipo cajón, verificando ausencia de deformaciones, corrosión y fisuras en las soldaduras. {resultado_por_estado}",
        "4.2": "Se realizó la inspección de los testeros, verificando su estado estructural y ausencia de deformaciones. {resultado_por_estado}",
        "4.3": "Se realizó la inspección de la ubicación y fijación de los topes mecánicos del puente/pluma. {resultado_por_estado}",
        "4.4": "Se realizó la inspección de los topes de goma del puente/pluma, verificando su fijación y estado de desgaste. {resultado_por_estado}",
        "4.5": "Se realizó la inspección de los barredores de riel del puente/pluma. {resultado_por_estado}",
        "4.6": "Se realizó la inspección del riel de rodadura del puente y/o pluma, verificando alineación y desgaste. {resultado_por_estado}",
        "4.7": "Se realizó la inspección de la vía de rodadura, verificando su nivelación y estado estructural. {resultado_por_estado}",
        "4.8": "Se realizó la verificación del apriete de los pernos de sujeción entre el testero y la viga tipo cajón. {resultado_por_estado}",
        "4.9": "Se realizó la inspección de los motorreductores de traslación del puente, verificando fugas, ruido y nivel de aceite. {resultado_por_estado}",
        "4.10": "Se realizó la inspección del eje de transmisión del puente, verificando alineación, acoples y ausencia de juego excesivo. {resultado_por_estado}",
        "4.11": "Se realizó la inspección y calibración de los frenos de los motores de traslación del puente, ajustando el air gap de acuerdo con lo recomendado por el fabricante. {resultado_por_estado}",
        "4.12": "Se realizó la inspección del rectificador de freno de los motores de traslación del puente. {resultado_por_estado}",
        "4.13": "Se realizó la inspección del limit switch de traslación del puente, verificando su correcto accionamiento. {resultado_por_estado}",
        "4.14": "Se realizó la inspección de las barras actuadoras del limit switch del puente, verificando su fijación y alineación. {resultado_por_estado}",
        "4.15": "Se realizó la inspección del piñón de transmisión de las ruedas del puente, verificando desgaste de dientes y engrase. {resultado_por_estado}",
        "4.16": "Se realizó la inspección de la plataforma de servicio y/o mantenimiento, verificando su estructura, superficie antideslizante y barandas de seguridad. {resultado_por_estado}",
        "4.17": "Se realizó la inspección de la escalera de acceso, verificando su fijación, peldaños y pasamanos. {resultado_por_estado}",
    },
    "Componentes eléctricos puente": {
        "3.1": "Se realizó la inspección de los tableros de fuerza y control del puente: gabinete, puertas, chapas, hermetismo, seguros y estado de pintura, aplicando limpia contacto y ajustando terminales y bornes. {resultado_por_estado}",
        "3.2": "Se realizó la inspección de los prensaestopas del tablero del puente, verificando su hermeticidad. {resultado_por_estado}",
        "3.3": "Se realizó la inspección y limpieza de los variadores de frecuencia del puente. {resultado_por_estado}",
        "3.4": "Se realizó la inspección de las resistencias de frenado del puente, verificando continuidad y estado físico. {resultado_por_estado}",
        "3.5": "Se realizó la inspección y limpieza de los contactores del inversor de giro del puente. {resultado_por_estado}",
        "3.6": "Se realizó la inspección y limpieza del contactor tetrapolar del puente. {resultado_por_estado}",
        "3.7": "Se realizó la inspección de los contactos auxiliares del tablero del puente. {resultado_por_estado}",
        "3.8": "Se realizó la inspección de las protecciones eléctricas del puente (fusibles, termomagnéticos y guardamotor). {resultado_por_estado}",
        "3.9": "Se realizó la inspección y limpieza del contactor de freno del puente. {resultado_por_estado}",
        "3.10": "Se realizó la inspección del rectificador de freno del puente. {resultado_por_estado}",
        "3.11": "Se realizó la inspección del transformador de control del puente, verificando su tensión de salida. {resultado_por_estado}",
        "3.12": "Se realizó la inspección y limpieza del contactor principal del puente. {resultado_por_estado}",
        "3.13": "Se realizó el apriete y verificación de las conexiones de los enchufes del tablero del puente. {resultado_por_estado}",
        "3.14": "Se realizó la inspección de las canalizaciones, bandejas, prensaestopas y flexibles eléctricos del puente. {resultado_por_estado}",
        "3.15": "Se realizó la inspección de los relés de contactos del tablero del puente, verificando su correcto accionamiento. {resultado_por_estado}",
    },
    "Sistemas de alimentación": {
        "4.1": "Se realizó la inspección de las barras encapsuladas y del enrollador de cable, verificando su fijación y funcionamiento. {resultado_por_estado}",
        "4.2": "Se realizó la inspección del carro toma corriente colector, verificando el estado de sus carbones y su contacto con la barra. {resultado_por_estado}",
        "4.3": "Se realizó la inspección del brazo de arrastre del sistema de alimentación, verificando su fijación y alineación. {resultado_por_estado}",
        "4.4": "Se realizó la inspección de las tapas inicial y final de las barras encapsuladas, verificando su fijación y hermeticidad. {resultado_por_estado}",
        "4.5": "Se realizó la inspección de los empalmes y uniones del sistema de alimentación, verificando su ajuste y continuidad eléctrica. {resultado_por_estado}",
        "4.6": "Se realizó la inspección de los cables planos de alimentación, verificando su estado físico y aislamiento. {resultado_por_estado}",
        "4.7": "Se realizó la inspección de los soportes de la barra encapsulada y/o riel tipo C, verificando su fijación y alineación. {resultado_por_estado}",
        "4.8": "Se realizó la inspección de los rieles tipo C, verificando su alineación y estado físico. {resultado_por_estado}",
        "4.9": "Se realizó la inspección de los carros porta cable deslizantes, de arrastre y fijos del sistema de alimentación. {resultado_por_estado}",
    },
    "Sistemas de mando": {
        "5.1": "Se realizó la inspección, limpieza, ajuste de terminales y mantenimiento del mando de control ({variante}). {resultado_por_estado}",
        "5.2": "Se realizó la inspección de los joystick/palancas del mando de control, verificando su accionamiento y retorno a posición neutra. {resultado_por_estado}",
        "5.3": "Se realizó la inspección de la carcasa del mando de control, verificando su integridad y hermeticidad. {resultado_por_estado}",
        "5.4": "Se realizó la inspección de los pulsadores de goma del mando de control, verificando su estado y respuesta al accionamiento. {resultado_por_estado}",
        "5.5": "Se realizó la inspección y prueba de funcionamiento del pulsador de parada de emergencia del mando de control. {resultado_por_estado}",
        "5.6": "Se realizó la inspección del selector de gancho (principal/auxiliar) del mando de control. {resultado_por_estado}",
        "5.7": "Se realizó la inspección de los indicadores de movimiento del mando de control, verificando su correspondencia con la operación real del equipo. {resultado_por_estado}",
        "5.8": "Se realizó la inspección del cable de control del mando, verificando su aislamiento y ausencia de daños externos. {resultado_por_estado}",
        "5.9": "Se realizó la inspección de los enchufes de la botonera y/o del sistema de mando inalámbrico, verificando su ajuste y estado. {resultado_por_estado}",
    },
    "Sistema audio visual": {
        "6.1": "Se realizó la inspección, limpieza, ajuste de terminales y mantenimiento de la sirena del equipo. {resultado_por_estado}",
        "6.2": "Se realizó la inspección, limpieza y mantenimiento de la circulina del equipo. {resultado_por_estado}",
        "6.3": "Se realizó la inspección de las luminarias del equipo, verificando su funcionamiento y fijación. {resultado_por_estado}",
        "6.4": "Se realizó la inspección del display indicador de peso, verificando su encendido y legibilidad. {resultado_por_estado}",
        "6.5": "Se realizó la inspección de las señales visuales/sonoras de movimiento de operación del equipo. {resultado_por_estado}",
        "6.6": "Se realizó la inspección de la señalética de indicador de capacidad del equipo, verificando que corresponda con la capacidad real del polipasto. {resultado_por_estado}",
        "6.7": "Se realizó la inspección del indicador de movimiento del equipo, verificando su correcto funcionamiento. {resultado_por_estado}",
    },
    "Otros": {
        "5.1": "Se realizó la limpieza general de la estructura y componentes del equipo, retirando polvo, grasa y suciedad acumulada. {resultado_por_estado}",
        "5.2": "Se realizó la inspección del estado de la pintura de la estructura del equipo, verificando presencia de corrosión u oxidación expuesta. {resultado_por_estado}",
        "5.3": "Se realizó la inspección visual de las soldaduras estructurales del equipo, verificando ausencia de fisuras o defectos visibles. {resultado_por_estado}",
    },
}


def cargar_textos(apps, schema_editor):
    ItemChecklistPlantilla = apps.get_model("checklist", "ItemChecklistPlantilla")

    actualizados = 0
    for sistema_nombre, items_dict in TEXTOS.items():
        for codigo, texto in items_dict.items():
            filas = ItemChecklistPlantilla.objects.filter(
                sistema__tipo_equipo__nombre="Grúa pórtico",
                sistema__nombre=sistema_nombre,
                codigo=codigo,
            )
            actualizados += filas.update(texto_plantilla=texto)

    total_esperado = sum(len(items_dict) for items_dict in TEXTOS.values())
    if actualizados != total_esperado:
        raise RuntimeError(
            f"Se actualizaron {actualizados} ítems, se esperaban {total_esperado}. "
            "Revisa que la migración 0002_cargar_plantilla_grua_portico ya esté aplicada "
            "y que los nombres de sistema/código coincidan."
        )


def vaciar_textos(apps, schema_editor):
    ItemChecklistPlantilla = apps.get_model("checklist", "ItemChecklistPlantilla")
    ItemChecklistPlantilla.objects.filter(
        sistema__tipo_equipo__nombre="Grúa pórtico"
    ).update(texto_plantilla="")


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0003_itemchecklistplantilla_texto_plantilla"),
        ("checklist", "0002_cargar_plantilla_grua_portico"),
    ]

    operations = [
        migrations.RunPython(cargar_textos, vaciar_textos),
    ]
