# Generated by Django 4.2.30 on 2026-08-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_delete_itemcotizacion'),
        ('checklist', '0004_texto_plantilla_grua_portico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='servicios.servicio')),
                ('sistema', models.ForeignKey(blank=True, help_text='Sistema del equipo al que corresponde, si aplica (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos', to='checklist.sistemachecklist')),
            ],
            options={
                'verbose_name': 'Hallazgo importante',
                'verbose_name_plural': 'Hallazgos importantes',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FotoHallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='hallazgos_fotos/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='checklist.hallazgo')),
            ],
            options={
                'ordering': ['hallazgo', 'orden'],
            },
        ),
    ]
