# Generated by Django 4.2.30 on 2026-08-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_hallazgo_fotohallazgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemachecklist',
            name='categoria',
            field=models.CharField(choices=[('mecanico', 'Mecánico'), ('electrico', 'Eléctrico'), ('generales', 'Generales')], default='mecanico', help_text='Agrupador para mostrar el checklist en pasadas (Mecánico → Eléctrico → Generales), como en el documento físico.', max_length=20),
        ),
        migrations.AlterField(
            model_name='respuestachecklist',
            name='estado',
            field=models.CharField(blank=True, choices=[('B', 'Buen estado'), ('R', 'Regular'), ('M', 'Mal estado / alto riesgo'), ('NA', 'No aplica')], max_length=2, null=True),
        ),
    ]
