# Generated by Django 4.2.30 on 2026-08-24 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('catalogos', '0001_initial'),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('anio', models.PositiveIntegerField(editable=False)),
                ('correlativo', models.PositiveIntegerField(editable=False)),
                ('codigo', models.CharField(editable=False, max_length=60, unique=True)),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En ejecución'), ('entregado', 'Entregado')], default='cotizado', max_length=20)),
                ('orden_compra', models.CharField(blank=True, max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('porcentaje_igv', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('monto_igv', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('fecha_cotizacion', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_ejecucion_inicio', models.DateField(blank=True, null=True)),
                ('fecha_ejecucion_fin', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='equipos.equipo')),
                ('equipos_medicion_usados', models.ManyToManyField(blank=True, related_name='servicios', to='catalogos.equipomedicion')),
                ('normas_aplicables', models.ManyToManyField(blank=True, related_name='servicios', to='catalogos.normaaplicable')),
                ('servicio_origen', models.ForeignKey(blank=True, help_text='Preventivo del que se originó este correctivo, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correctivos_generados', to='servicios.servicio')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='clientes.ubicacion')),
            ],
            options={
                'ordering': ['-anio', '-correlativo'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='servicios.servicio')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='servicios.servicio')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_cotizacion', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Ítem de cotización',
                'verbose_name_plural': 'Ítems de cotización',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En ejecución'), ('entregado', 'Entregado')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='servicios.servicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['servicio', 'fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='FirmaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_damol', models.CharField(blank=True, max_length=150)),
                ('fecha_damol', models.DateField(blank=True, null=True)),
                ('firma_damol', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('nombre_cliente', models.CharField(blank=True, max_length=150)),
                ('fecha_cliente', models.DateField(blank=True, null=True)),
                ('firma_cliente', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_aprobacion', to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='FichaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('especificaciones_equipo', models.JSONField(blank=True, default=dict, help_text='Snapshot editable en campo de las specs del equipo.')),
                ('objetivo', models.TextField(blank=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('trabajos_previos', models.TextField(blank=True)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion', to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='SecuenciaCorrelativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('anio', models.PositiveIntegerField()),
                ('ultimo_valor', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Secuencia de correlativo',
                'verbose_name_plural': 'Secuencias de correlativo',
                'unique_together': {('tipo_servicio', 'cliente', 'anio')},
            },
        ),
    ]
