# Generated by Django 4.2.30 on 2026-08-26 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conclusion',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='conclusion',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='condiciones_ambientales',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conclusion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusiones', to='servicios.servicio'),
        ),
    ]
