# Generated by Django 4.2.30 on 2026-08-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_conclusion_options_conclusion_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='elaborado_por',
            field=models.CharField(blank=True, help_text='Nombre de quien elabora el informe, tal como debe aparecer en la portada.', max_length=150),
        ),
    ]
