# Generated by Django 4.2.30 on 2026-08-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_elaborado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaservicio',
            name='especificaciones_equipo',
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='especificaciones_polipasto',
            field=models.JSONField(blank=True, default=dict, help_text='Specs del polipasto (clasificación, velocidades, voltajes, etc.).'),
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='especificaciones_trolley',
            field=models.JSONField(blank=True, default=dict, help_text='Specs del trolley (span, diámetro de cable, torsión, etc.).'),
        ),
    ]
