# Generated by Django 4.2.30 on 2026-08-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_remove_fichaservicio_especificaciones_equipo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCotizacion',
        ),
    ]
