# Generated by Django 4.2.30 on 2026-08-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_alerta_cotizado', models.PositiveIntegerField(default=5, help_text="Si un servicio lleva más de este número de días en estado 'Cotizado', se marca en alerta.", verbose_name='Días para alertar una cotización sin aprobar')),
                ('dias_alerta_ejecucion', models.PositiveIntegerField(default=7, help_text="Si un servicio lleva más de este número de días en estado 'En ejecución', se marca en alerta.", verbose_name='Días para alertar un trabajo atrasado')),
            ],
            options={
                'verbose_name': 'Configuración de alertas',
                'verbose_name_plural': 'Configuración de alertas',
            },
        ),
    ]
