# Generated by Django 4.2.30 on 2026-08-30 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('tecnico', 'Técnico'), ('comercial', 'Comercial'), ('administrador', 'Administrador')], max_length=20)),
                ('tecnico', models.ForeignKey(blank=True, help_text="Solo si el rol es Técnico: qué registro de personal corresponde a este usuario, para filtrar 'Mis servicios'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='personal.tecnico')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
