# Generated by Django 4.2.30 on 2026-08-24 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_informe', models.CharField(blank=True, max_length=50)),
                ('archivo_pdf', models.FileField(upload_to='informes/%Y/%m/')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='servicios.servicio')),
            ],
            options={
                'ordering': ['-generado_en'],
            },
        ),
    ]
