# Generated by Django 4.2.30 on 2026-08-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config_informe/')),
                ('encabezado_codigo', models.CharField(default='JP-F-007', max_length=30)),
                ('encabezado_version', models.CharField(default='04', max_length=10)),
                ('encabezado_fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('normatividad_texto', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración del informe',
                'verbose_name_plural': 'Configuración del informe',
            },
        ),
        migrations.AlterField(
            model_name='informegenerado',
            name='generado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
