# Generated by Django 4.2.30 on 2026-08-30 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_delete_itemcotizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0003_seed_configuracion_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninforme',
            name='propuesta_intro_texto',
            field=models.TextField(blank=True, default='De nuestra consideración:\n\nEs un agrado saludarlos cordialmente. De acuerdo a sus requerimientos, presentamos nuestra propuesta técnico-económica para el desarrollo del servicio descrito en el presente documento, garantizando el cumplimiento de los estándares de seguridad y la normativa aplicable vigente en mantenimiento de equipos de izaje.'),
        ),
        migrations.AddField(
            model_name='configuracioninforme',
            name='propuesta_terminos_adicionales',
            field=models.TextField(blank=True, help_text='Cláusulas fijas adicionales, una por línea (forma de pago, plazo, etc.).'),
        ),
        migrations.AddField(
            model_name='configuracioninforme',
            name='propuesta_validez_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='PropuestaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='propuestas/%Y/%m/')),
                ('generado_en', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propuesta_comercial', to='servicios.servicio')),
            ],
            options={
                'ordering': ['-generado_en'],
            },
        ),
    ]
