# Generated by Django 4.2.30 on 2026-09-05 15:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_configuracioninforme_propuesta_intro_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informegenerado',
            name='archivo_pdf',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='informes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='propuestacomercial',
            name='archivo_pdf',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='propuestas/%Y/%m/'),
        ),
    ]
