# Generated by Django 4.2.30 on 2026-08-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_medicion', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Grupo de mediciones',
                'verbose_name_plural': 'Grupos de mediciones',
                'ordering': ['servicio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='FilaMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='mediciones.grupomedicion')),
            ],
            options={
                'ordering': ['grupo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ColumnaMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='mediciones.grupomedicion')),
            ],
            options={
                'ordering': ['grupo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ValorMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=50)),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='mediciones.columnamedicion')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='mediciones.filamedicion')),
            ],
            options={
                'unique_together': {('fila', 'columna')},
            },
        ),
    ]
