# Generated by Django 4.2.30 on 2026-08-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('cargo_habitual', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='MaterialHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unidad', models.CharField(default='Und', max_length=30)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_herramientas', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Material / herramienta',
                'verbose_name_plural': 'Materiales y herramientas',
                'ordering': ['servicio', 'item'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificacion', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='certificaciones_tecnicos/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='personal.tecnico')),
            ],
            options={
                'ordering': ['tecnico', '-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='PersonalEjecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_ejecutor', to='servicios.servicio')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to='personal.tecnico')),
            ],
            options={
                'verbose_name': 'Personal ejecutor',
                'verbose_name_plural': 'Personal ejecutor',
                'ordering': ['servicio', 'id'],
                'unique_together': {('servicio', 'tecnico')},
            },
        ),
    ]
