# Generated by Django 4.2.30 on 2026-09-05 15:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciontecnico',
            name='archivo',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificaciones_tecnicos/'),
        ),
    ]
