# Generated by Django 4.2.30 on 2026-08-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, help_text='TAG del equipo.', max_length=50)),
                ('marca_estructura', models.CharField(blank=True, max_length=100)),
                ('marca_polipasto', models.CharField(blank=True, max_length=100)),
                ('capacidad_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('especificaciones', models.JSONField(blank=True, default=dict, help_text='Specs técnicas variables según tipo de equipo (span, voltajes, velocidades, etc.).')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='clientes.cliente')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='equipos.tipoequipo')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='clientes.ubicacion')),
            ],
            options={
                'ordering': ['cliente', 'tipo_equipo', 'codigo_interno'],
            },
        ),
    ]
