# Generated by Django 4.2.30 on 2026-08-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipos_fotos/'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='foto_ubicacion',
            field=models.ImageField(blank=True, null=True, upload_to='equipos_fotos/'),
        ),
    ]
