# Generated by Django 4.2.30 on 2026-08-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('codigo_corto', models.CharField(help_text='Código corto usado en los correlativos de servicio, ej. VOLCAN.', max_length=20, unique=True)),
                ('ruc', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150)),
                ('contacto_telefono', models.CharField(blank=True, max_length=30)),
                ('contacto_email', models.EmailField(blank=True, max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='clientes.cliente')),
            ],
            options={
                'ordering': ['cliente', 'nombre'],
                'unique_together': {('cliente', 'nombre')},
            },
        ),
    ]
