# Generated by Django 4.2.30 on 2026-08-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('servicios', '0005_delete_itemcotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_indirectos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_utilidad_servicio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_utilidad_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal_mano_obra', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('subtotal_logistica', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('subtotal_equipos', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('subtotal_materiales', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('monto_indirectos', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('monto_utilidad_servicio', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('monto_utilidad_repuestos', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('subtotal_servicio', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('subtotal_repuestos', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_cotizacion', to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_material', to='cotizaciones.detallecotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_cotizacion', to='inventario.producto')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(help_text="Rol/cargo, ej. 'Técnico especialista'.", max_length=255)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_mano_obra', to='cotizaciones.detallecotizacion')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(help_text="Ej. 'Pasaje aéreo Lima-Cusco', 'Hospedaje 3 noches'.", max_length=255)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_logistica', to='cotizaciones.detallecotizacion')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(help_text="Ej. 'Alquiler de grúa telescópica'.", max_length=255)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_equipo', to='cotizaciones.detallecotizacion')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
    ]
