# Generated by Django 4.2.30 on 2026-08-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecotizacion',
            options={'verbose_name': 'Detalle de cotización', 'verbose_name_plural': 'Detalles de cotización'},
        ),
        migrations.AlterModelOptions(
            name='itemequipo',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Ítem de equipo', 'verbose_name_plural': 'Ítems de equipos'},
        ),
        migrations.AlterModelOptions(
            name='itemlogistica',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Ítem de logística', 'verbose_name_plural': 'Ítems de logística'},
        ),
        migrations.AlterModelOptions(
            name='itemmanoobra',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Ítem de mano de obra', 'verbose_name_plural': 'Ítems de mano de obra'},
        ),
        migrations.AlterModelOptions(
            name='itemmaterial',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Ítem de material', 'verbose_name_plural': 'Ítems de materiales'},
        ),
    ]
