# Generated by Django 4.2.30 on 2026-08-29 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_alter_detallecotizacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProvisionDamol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_provision_damol', to='cotizaciones.detallecotizacion')),
            ],
            options={
                'verbose_name': 'Ítem de provisión de Damol',
                'verbose_name_plural': 'Ítems de provisión de Damol',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemProvisionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_provision_cliente', to='cotizaciones.detallecotizacion')),
            ],
            options={
                'verbose_name': 'Ítem de provisión del cliente',
                'verbose_name_plural': 'Ítems de provisión del cliente',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_exclusion', to='cotizaciones.detallecotizacion')),
            ],
            options={
                'verbose_name': 'Ítem de exclusión',
                'verbose_name_plural': 'Ítems de exclusión',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemAlcance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_alcance', to='cotizaciones.detallecotizacion')),
            ],
            options={
                'verbose_name': 'Ítem de alcance',
                'verbose_name_plural': 'Ítems de alcance',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
    ]
