# Generated by Django 4.2.30 on 2026-08-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_itemprovisiondamol_itemprovisioncliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mano_obra', 'Mano de obra'), ('logistica', 'Logística'), ('equipo', 'Equipos (alquiler)'), ('alcance', 'Alcance del servicio'), ('exclusion', 'Exclusiones'), ('provision_cliente', 'Provisiones del cliente'), ('provision_damol', 'Provisiones de Damol')], max_length=30)),
                ('texto', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ítem de catálogo',
                'verbose_name_plural': 'Ítems de catálogo',
                'ordering': ['tipo', 'texto'],
                'unique_together': {('tipo', 'texto')},
            },
        ),
    ]
